/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ClassPie: typeof import('./src/components/ClassPie.vue')['default']
    ClassSummaryCloud: typeof import('./src/components/ClassSummaryCloud.vue')['default']
    ClassThemeRiver: typeof import('./src/components/ClassThemeRiver.vue')['default']
    Cloud3D: typeof import('./src/components/Cloud3D.vue')['default']
    DynamicBar: typeof import('./src/components/DynamicBar.vue')['default']
    ElAside: typeof import('element-plus/es')['ElAside']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ForceChart: typeof import('./src/components/ForceChart.vue')['default']
    HeapMapChart: typeof import('./src/components/HeapMapChart.vue')['default']
    IconCommunity: typeof import('./src/components/icons/IconCommunity.vue')['default']
    IconDocumentation: typeof import('./src/components/icons/IconDocumentation.vue')['default']
    IconEcosystem: typeof import('./src/components/icons/IconEcosystem.vue')['default']
    IconSupport: typeof import('./src/components/icons/IconSupport.vue')['default']
    IconTooling: typeof import('./src/components/icons/IconTooling.vue')['default']
    IndicatorChart: typeof import('./src/components/IndicatorChart.vue')['default']
    NewBar: typeof import('./src/components/NewBar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
